### ISSUE TITLE
NoClassDefFoundError crash

### ISSUE THREAD

**Issue by TheRandomLabs** [LatvianModder/YABBA#1]
I got a crash while trying to run Yabba on my server. I'm pretty sure it's caused by the registration of models on the server-side.
http://pastebin.com/YtTUGVi2

**Comment by CelticChristoph** [comment]
MC Version: 1.10.2
Forge version: 12.18.3.2185

I am also receiving this error while trying to launch a server with YABBA.

https://gist.github.com/CelticChristoph/44d4f904413f6bd7de0427b2f0c7b4b1

**Comment by DeadSix27** [comment]
Same error, seems to be client-only mod so far.
https://gist.github.com/DeadSix27/adf7539aa9f82e2be435a67d803561b3

**Comment by LatvianModder** [comment]
Does http://mods.latmod.com/YABBA/1.10.2-0.1.1/ fix it?
