### ISSUE TITLE
Access barrel settings/lock barrel

### ISSUE THREAD

**Issue by robertgdalton** [LatvianModder/YABBA#10]
So when I look at the barrel with an empty hand obviously the gear appears on the left and the padlock on the right but I can't for the life of me figure out how to access settings or how to lock the barrel? Help please?

**Comment by LatvianModder** [comment]
Shift-right click with empty hand on the gears icon / lock icon

**Comment by lifeofllama** [comment]
Same problem here. Did what you said but no response. Could be visual haven't checked
