### ISSUE TITLE
Crash with using hammer

### ISSUE THREAD

**Issue by NightcoreIsla** [LatvianModder/YABBA#101]
Hello i add this mod in my SevTech Server
but when i use the hammer the client will crash
i hope can fix it thanks
here is report
https://drive.google.com/file/d/1RGunIrnrsGhmuoVACQo5TaGRHWescjFn/view?usp=sharing
Minecraft Launcher show:
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: com.latmod.yabba.gui.GuiSelectModel$ButtonModel.setPosAndSize(IIII)Lcom/feed_the_beast/ftblib/lib/gui/Widget;

i just first time use the github Issues and i don't speak english well
so if any u want me do for better can tell me
thanks again

**Comment by NightcoreIsla** [comment]
oh and i hope the yabba can face on top or bottom again
it is useful for save space and decoration
thx

**Comment by LatvianModder** [comment]
Update FTBLib
