### ISSUE TITLE
Certain items stuck in anti barrel

### ISSUE THREAD

**Issue by gitterrost4** [LatvianModder/YABBA#108]
When I put certain items (an engineer's toolbox from immersive engineering and an ender staff from reliquary in my case) into the anti barrel, I can't take it out. If I try, it goes into my inventory, but is just there as a ghost item (picking it up will result in it vanishing). When I look into the anti barrel again, the item is still in there. 

I am playing on the current version of Modern Skyblock 3.

**Comment by shadus** [comment]
I'm also seeing this bug, getting it with "Engineer's Blueprint" from Immersive Engineering and "Ender Staff" from Reliquary.  Also, further testing shows I can remove them by putting a hopper under it and sucking them out into a chest... then they behave normally, but if I pull them out to my inventory, not so much.

(Also Playing Modern Skyblock 3 current version as of 11/4/18)
