### ISSUE TITLE
Barrel Settings not working

### ISSUE THREAD

**Issue by aaronhowser1** [LatvianModder/YABBA#109]
This is using FTBLib-5.4.0.70 and YABBA-1.1.2.29.

With default settings:
![image](https://user-images.githubusercontent.com/15698722/49707902-ef490e80-fbf2-11e8-8353-ca4e999dfadb.png)
![image](https://user-images.githubusercontent.com/15698722/49707900-eb1cf100-fbf2-11e8-84bd-e08c480de6c4.png)

With all settings enabled:
![image](https://user-images.githubusercontent.com/15698722/49707920-fec85780-fbf2-11e8-8432-52af040b1d80.png)
![image](https://user-images.githubusercontent.com/15698722/49707924-012ab180-fbf3-11e8-94d2-e56bc391defe.png)
The settings stay saved when I reopen the barrel settings GUI

**Comment by LatvianModder** [comment]
Hm. Does relogging fix that?

**Comment by aaronhowser1** [comment]
Looks like it does. When I logged back in, everything was on and working. I turned some stuff off which didn't stick, then relogged and it got fixed.

**Comment by LatvianModder** [comment]
Placing a breaking a block in front of it also may fix it
