### ISSUE TITLE
Graphical error when changing state of connected ender io item ducts [Caused by Sponge?]

### ISSUE THREAD

**Issue by Xyrys** [LatvianModder/YABBA#11]
Hi. 

Been experiencing a weird bug.  I have textured all my barrels black clay.. Looks sweet..  However.  Every time I connect an ender io item duct anywhere thats connected to the ones on the backs of the barrels ALL the textures change back to the normal one and it then displays no icon as well.  Hoving over it doesnt show the names etc and number.  As soon as you right click them again, they work perfectly until the next time you change a setting on an item duct etc..   I have attached 2 files.. 1 before I click on an item duct, and 1 after..
Hopefully  its an easy fix :-)

Xyrys.

![2017-04-11_23 45 59](https://cloud.githubusercontent.com/assets/10042954/24912482/9529d368-1f11-11e7-9721-7ba1d43f8602.png)
![2017-04-11_23 47 13](https://cloud.githubusercontent.com/assets/10042954/24912490/98e51a8a-1f11-11e7-887a-df80764cd29e.png)

**Comment by LatvianModder** [comment]
Huh, very weird. F3 + A doesnt fix it?

**Comment by Xyrys** [comment]
No F3+A doesn't fix it.  Going to nether or mining dimension does however, or right clicking each barrel..

X

**Comment by Xyrys** [comment]
Even weirder.. Just noticed this..  just checked it 3 times.. and same happens.. the barrels not changing are all connected as well.  same as the ones right next to them.
![2017-04-12_00 38 46](https://cloud.githubusercontent.com/assets/10042954/24914825/c137ba7c-1f18-11e7-9de8-4684fc3ccc66.png)

However as you can see in the next picture.. the ones not affected are on the other side of a chunk boundary.  However..  Adding a duct in another chunk still causes this..
![2017-04-12_00 39 59](https://cloud.githubusercontent.com/assets/10042954/24914833/c6fd88b0-1f18-11e7-9b11-558e4084149e.png)

X

**Comment by Xyrys** [comment]
Updated to 1.5.3  Have not seen this happen yet, by doing duct changes in another chunk yet.  I will be redoing the wiring so to speak in my storage room later tonight, so I should see if its still happening then.

X

**Comment by Xyrys** [comment]
Still happens. After rebuilding the room.  However now its only on breaking any ender io duct connected to the barrels, or the input/output line.

X

**Comment by Hodel1** [comment]
Same bug with Storage Bus from Applied Energistics 2.

Tested on FTB 1.5.3 with 1.10.2-0.4.3 and AE2 rv4-alpha-11

**Comment by LatvianModder** [comment]
It must be some desync bug

**Comment by LatvianModder** [comment]
Is spongeforge or anything else weird present?

**Comment by Hodel1** [comment]
Yes. Latest Spongeforge version.
But is it a Serverside or Clientside problem?

Spongeforge is running serverside only.

**Comment by Xyrys** [comment]
I however am not running anything but the base pack of FTB Beyond.  No extra mods.  Home server using base forge, but occurs in my base on a whitelist server as well.  Happens everytime I use ender IO ducts, and only on connected nodes from extra utils.

I guess the oddest part is reloading the chunks doesnt fix it.. I have to leave the area and then come back in either from nether or a long run away.

X

**Comment by LatvianModder** [comment]
That most likely is server side issue. Try removing spongeforge and test then

**Comment by Xyrys** [comment]
Just to add..  I am not using sponge.. Its not on my server, and its not on the whitelist server I was connecting to.  So.. I can't see how its a sponge error..  Just adding this incase somehow thats not clear..

X

**Comment by LatvianModder** [comment]
See if it works on latest version (0.5.1). if not, I have no idea how to fix it

**Comment by stensch** [comment]
I have Ender IO ducts connected to multiple barrels and they don't glitch. However, adding a fully built smeltery from Tinkers to the chunk does. As soon as I destroy the smeltery controller and reset the barrels, they work again.

**Comment by Pwootage** [comment]
I am having the same texture-disappearing issue on 1.10.2/0.5.1 on my server, and (as far as I am aware) I do not have anything sponge related installed.

This pack was originally based on Beyond, although it has some significant differences at this point.

**Comment by LatvianModder** [comment]
I wonder if you can replicate it in 1.11

**Comment by stensch** [comment]
Tried to test this on 1.11, but got this issue: #25

**Comment by LatvianModder** [comment]
That issue wasn't related

**Comment by einsteinsci** [comment]
I'm also having this exact same issue in a customized Sky Factory 3 (for 1.10.2) with YABBA 0.5.1. I'm on SSP so this is not a sponge-related bug.
