### ISSUE TITLE
Recent Update Broke Molten Metal Barrel Textures

### ISSUE THREAD

**Issue by DJBaphomet** [LatvianModder/YABBA#110]
So, when Stoneblock 2 updated to 1.2.0, YABBA updated in it. Something caused all Molten Metal textures to go missing on YABBA Barrels, as they are all grey like in the picture provided below.
![image](https://user-images.githubusercontent.com/44253613/51474549-f8261780-1d3c-11e9-8de6-8ce2a128c712.png)
This is slightly annoying as I paint my barrels with the molten metal coordinated with the Essence/Metal in it.

**Comment by LatvianModder** [comment]
Test with https://jenkins.latmod.com/job/YABBA/34/
