### ISSUE TITLE
Locked state ignored when automatically putting items into a barrel

### ISSUE THREAD

**Issue by darkphan** [LatvianModder/YABBA#111]
If a barrel is locked, and all the items removed from the barrel you can put anything else in the barrel via hoppers, AE2 storage bus/etc, or other methods of piping items into the barrel.

To replicate:

- Place barrel
- Put cobblestone into barrel
- Lock barrel
- Remove cobblestone
- Place hopper facing into the barrel
- Put anything other than cobblestone into the hopper

The barrel state remains locked but the new item will now be in the barrel. This is not the expected behavior.

**Comment by 016Nojr** [comment]
Can confirm this is happening using YABBA version 1.1.2.34

Forge 5.2807
FTBLib 5.4.1.78

**Comment by LatvianModder** [comment]
Fixed in 35

**Comment by newcodher** [comment]
Not fixed in YABBA-1.1.2.39.jar.

Empty ***locked*** barrels still allows importation if imported into through storage bus or hopper.

**Comment by LatvianModder** [comment]
I don't see an issue with empty locked barrels accepting items
