### ISSUE TITLE
locking barrel while using barrel connector

### ISSUE THREAD

**Issue by DubbaThony** [LatvianModder/YABBA#112]
Hello,
Im playing stoneblock 2 and I was super hyped for this mod (I honestly <3 old jabba back in 1.6.4) so thanks for this mod :)

Anyway, back on topic.

**Version**:
YABBA 1.1.2.31

**Severity**:
major - loss of function while using in any form of automation (so most of the times)

**Summary**:
Items inserted into barrels via barrel connector seems to ignore barrel's lock.
You can reproduce the bug orginal way I found out, or you can just simply use vanilla hopper.

Here are **steps to reproduce**:
1. I've set up few barrels and connected them with barrel connector.
2. I've locked every barrel with item I wanted it to hold.
3. I've added ME storage bus and set it priority highest in system
4. I've drained all items from barrel via ME system (can be done by hand, works too).
5. I've added non-barrel whitelisted item into applied energistics.

**Expected result**:
Locked barrel should retain 0 items and locked, let's say redstone, and inserted item should land in ME drives.

**Actual result**:
AE2 bypasses barrel lock, the item lands in barrel even if it's lets say cobblestone, not redstone.

**Comment by LatvianModder** [comment]
Even without connector barrels ignored lock, it's been fixed already https://jenkins.latmod.com/job/YABBA/changes
