### ISSUE TITLE
Antibarrel keeping several items

### ISSUE THREAD

**Issue by TheKrowi** [LatvianModder/YABBA#113]
Related to https://github.com/LatvianModder/YABBA/issues/81.

My anti barrel refuses to give me the Common Lootbag from Loot Bags mod. Shift clicking, dragging, nothing works. Modpack I'm playing is PO3 3.0.36. YABBA is at 1.1.2.39. Loot Bags is 1.12.2-2.5.7.

I am able to get it out though if I use the EnderIO item conduit to extract the item. It was put in that way too.

**Comment by LatvianModder** [comment]
Reopen issue if it still exists
