### ISSUE TITLE
Chest Movement tools cause duplication

### ISSUE THREAD

**Issue by McKitten** [LatvianModder/YABBA#115]
YABBA-1.1.2.41
ChestTransporter-1.12.2-2.8.8
Cyclic-1.12.2-1.17.16

In an attempt to not loose 2 of the contents to an open inventory spot every time a barrel is moved, I tried using the Obsidian Chest Transporter and ended up with a 2nd empty barrel loose on the floor and the full barrel (with all contents) in my inventory tool. This was the same case for the Cyclic Bag of Holding.

**Comment by LatvianModder** [comment]
At least its only an empty barrel. You can use Barrel Wrench to drop barrels properly

**Comment by LatvianModder** [comment]
Reported to mod author: https://github.com/cubex2/chesttransporter/issues/32
