### ISSUE TITLE
applied integrations

### ISSUE THREAD

**Issue by bick88** [LatvianModder/YABBA#116]
YABBA-1.1.2.41

it seems your mod causse an issue with Applied integrations 

it try too put Applied integrations in different modpack and in each case, i have the same issue : a crash.

Same issue  : at com.latmod.yabba.client.YabbaClient.loadModelsAndSkins(YabbaClient.java:119)

https://pastebin.com/B9rDfNjh modpack Ozone 3

https://pastebin.com/Q35w5Dme mod pack FTB stoneblock 2

issue open in Applied integrations : https://github.com/AzazeII/Applied-Integrations/issues/5

**Comment by LatvianModder** [comment]
From what I can tell, some fluid's still icon is null, which should never happen. Blame other mod. Still, I patched it to ignore such fluids

**Comment by AzazeII** [comment]
Yes, i absolutely forgot about LiquidAIEnergy class, used only as wrapper for energies in my mod :c
From issue on Applied integrations page:
> From [LatvianModder/YABBA#116](https://github.com/LatvianModder/YABBA/issues/116):
> 
> > From what I can tell, some fluid's still icon is null, which should never happen. Blame other mod. Still, I patched it to ignore such fluids
> 
> If this issue is caused by null fluid's icons, than i think i can fix it. And yes, these fluids have no icons, because they was used as energy in 1.7.10 version, because AE Api in 1.7.10 didn't provided methods to create own storage channel. But now it can be fixed, wait for 8.0.7 update
