### ISSUE TITLE
Enhancement suggestion

### ISSUE THREAD

**Issue by Xyrys** [LatvianModder/YABBA#12]
Hi,

Have been using your mod for a good 3 hrs now..  It would be great if there was a way to see on the front if the barrel was upgraded when you mouse over..  Maybe a small icon. Perhaps a number..  1 2 3 4 OO etc..

Thats infinity not OO.. :-p

X

**Comment by LatvianModder** [comment]
That will be part of TOP integration, but I have an idea. How about the settings gear changes color based on tier? The front is already pretty stuffed

**Comment by Xyrys** [comment]
That would be simply awesome..  On another note.. What exactly is it for..  I saw it and thought OMG what can I change, but its empty. :-0

X

**Comment by LatvianModder** [comment]
In newer versions there are 2 options you can change already, but even in older ones (pack might not be updated) it's for upgrade settings - Redstone Output and Hopper both have config options

**Comment by Xyrys** [comment]
Hmm.. Might upgrade FTB Beyond to the latest tonight then.

**Comment by Xyrys** [comment]
BTW the Icon changing when its upgraded is absolutely awesome..  Just noticed after I updated to 1.5.3

Great work..

X
