### ISSUE TITLE
AntiBarrel

### ISSUE THREAD

**Issue by applemes** [LatvianModder/YABBA#122]
I just started a new singleplayer on PO3, before I used Technic Launcher, and there was the AntiBarrel in the pack, but now using twitch I can't find it. The Yabba mod is still in the pack, and there are other barrels, but I can't craft the anti barrel, it isnt in the JEI, and I can't craft it just using the actual recipe

**Comment by LatvianModder** [comment]
Then it's probably removed by modpack

**Comment by Pultex** [comment]
Yes they seem to have removed it for a reason.
For some reason the the Anti Barrel in PO3 will crash your server in SP or MP.
If you open it you will be fine, when you try to leave the anti barrel GUI the server will CRASH.
Opening the inventory while in the GUI of the anti barrel will do this.
If you exit the GUI with "ESC" key you will be fine, though how many time will you forget and crash the server.
