### ISSUE TITLE
Exception in server tick loop with Simple Dimensions

### ISSUE THREAD

**Issue by LazCreations** [LatvianModder/YABBA#127]
Getting a pretty serious crash with the latest Yabba and Simple Dimensions installed at the same time.
This crash happens when creating a new Dimension and Yabba causes an exception in server tick loop.
Removed all other mods except Yabba, FTBLib and Simple Dimensions.
The world will no longer load after the crash happens so don't do it on a preexisting world.

Tried this on multiple versions of forge starting from the recommend forge-14.23.5.2768 to the latest forge-14.23.5.2836.

[crash-2019-04-27_17.29.41-server.txt](https://github.com/LatvianModder/YABBA/files/3123625/crash-2019-04-27_17.29.41-server.txt)

**Comment by LatvianModder** [comment]
Hm. I would say this is a Simple Dimensions bug, because it somehow doesnt initialize world properly, but I think I can fix this on my end too. You should report this to them too

**Comment by LazCreations** [comment]
Cheers, 
I submitted a bug report about a week ago with Simple Dimensions but wasn't sure if it was a bug with Yabba or Simple Dimensions specifically so posted here also.
Haven't heard back from lumien yet.

[Link to Simple Dimensions Bug](https://github.com/lumien231/Simple-Dimensions/issues/21)
