### ISSUE TITLE
Weird glitch with barrels not retaining skins

### ISSUE THREAD

**Issue by zzyzzyzzx** [LatvianModder/YABBA#13]
Good day,

Im playing on a public server with sponge installed, and plugins like GP and stuff.

not sure whats causing it but when you setup a barrel and it it with like a hammer or something, it will stay there (the textures you picked) but after a certain amount of time, it stops working and the skins revert back to default, is there a config or something that might be causing it to do this, or could it be happening with sponge?

**Comment by Xyrys** [comment]
If you right click it does it go back to its skin ?

X

**Comment by LatvianModder** [comment]
Might be a duplicate of #11

**Comment by zzyzzyzzx** [comment]
There was more, but gyazo and their pay us money for longer:

https://gyazo.com/09bf2885c33b3350c5ac16d76efd0d07


basically i have to right click on the barrels every time to get them to show whats in them

https://i.gyazo.com/ff319e7340394d6bcfc8f88d9e2619db.png

the picture is the settings i have on the barrel, sometimes when i come back from other Dims it works, sometimes not, its not just me, basically everyone on the server has been having this issue

**Comment by LatvianModder** [comment]
That actually might be sponge's fault. Not sure, but that's the only thing I can blame because it works fine everywhere else

**Comment by zzyzzyzzx** [comment]
that what i was assuming, hope you might have had an idea of something for it

**Comment by LatvianModder** [comment]
Not sure why sponge blocks network data, because to sync barrel data I use custom stuff, not even vanilla.. Uh.. #blamesponge?

**Comment by zzyzzyzzx** [comment]
weird i moved them to a different location around 200 blocks away and worked like a charm, also sorry i forgot to close
