### ISSUE TITLE
YABBA FTB Lib StoneBlock 2 Crash

### ISSUE THREAD

**Issue by DexarCraft** [LatvianModder/YABBA#131]
I encountered a strange crash ( strange cuz sometimes it crashes and sometimes it doesn't). Basically when I'm opening my Antichest from YABBA the game crashes and it suggestes that YABBA and FTB Lib can be the causes.

Here's the crash report : https://paste.dimdev.org/uqepedihab.mccrash

**Comment by jmmmmmmmmmm10** [comment]
same probmle 
https://paste.dimdev.org/qufucavofa.mccrash
