### ISSUE TITLE
Item Barrel duplication bug

### ISSUE THREAD

**Issue by Zentraxius** [LatvianModder/YABBA#132]
If using a Moving Wand from Not Enough Wands to pickup a loaded item barrel, the wand picks up the full barrel but an empty barrel drops in the world, allowing you to place the full barrel and get an extra empty barrel for free. This can be repeated indefinitely.

**Comment by LatvianModder** [comment]
This is a Not Enough Wands block, before removing block its supposed to remove tile entity from world

**Comment by Bass2style** [comment]
same issue with Chest Transporter, so i think it's Yabba that not correctly handle those "transport methods".
