### ISSUE TITLE
[Suggestion] Moving mechanic (e.g. Dolly)

### ISSUE THREAD

**Issue by confuded** [LatvianModder/YABBA#14]
Hi!

Would love to see the dolly [like they have in JABBA](https://ftbwiki.org/Dolly) (I played FTB Infinity in the past). Or at least some non-OP mechanic for moving barrels.

Great work!

I am from Riga =P. My Latvian is a little rusty though... 

P.S. I am on whatever version FTB Evolved is on atm.

**Comment by 0-mr-redstone-0** [comment]
Barrels keep their inventory when broken, (tested on v0.5.0)

dolly's don't really de-overpower the keep inventory mechanic. just makes it slightly more tedious.

unless you make the dolly majorly expensive in terms of crafting cost

**Comment by confuded** [comment]
Heh, now it works! Weird. Before when I tried braking a barrel it wouldn't break when there was something in there.
