### ISSUE TITLE
[BUG] Item Dupe

### ISSUE THREAD

**Issue by jaspercayne** [LatvianModder/YABBA#15]
I don't know if this was intended or not, but I just made 5 barrels and 5 void upgrades. I tossed them together in the crafting grid and when I took them off the grid I had 5 void barrels (as expected), but also 4 void upgrades and 4 regular barrels. It looks like an upgrade is applied to the entire stack at once, but also then duplicates both the barrels and the upgrade items too.

TLDR; 5 barrels and 5 void upgrades in the crafting grid makes 5 void barrels, 4 regular barrels, and 4 void upgrades

**Comment by LatvianModder** [comment]
uh oh

**Comment by jaspercayne** [comment]
It only happened with 5 each, for the record. I tried putting the duplicate
barrels in the grid with the remaining void upgrades, and it worked as
expected. I haven't tried to reproduce it yet, but I can certainly try it
again later today with more rigorous testing of different stack numbers.
For what it is worth, (I don't believe it matters, but for completeness)
this was in my personal 2x2 grid, not a 3x3 table.

**Comment by LatvianModder** [comment]
I can't reproduce it, can you?
