### ISSUE TITLE
Antibarrel crashes players when picked up.

### ISSUE THREAD

**Issue by jinks** [LatvianModder/YABBA#16]
I accidentally picked up an antibarrel and immediately crashed to an oversized NBT tag.
(io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097158bytes where max allowed: 2097152)

I kinda expected this to happen when I saw that it stores its content as NBT and tried to avoid picking it up, but accidents happen and in the long run that's just not a useful solution.

I guess you will either have to limit the contents or use a custom storage format to work around Minecraft's limitations.

**Comment by LatvianModder** [comment]
Well this sucks. Any idea how many items approximately were in the barrel?

**Comment by jinks** [comment]
If NBTExplorer is to be trusted and I was reading its info right, about 249k items. That would roughly correlate with other stuff I got out of the mob farm. So, in short, **a lot**.

I misused it as a mob farm trash can that didn't need a filter, should probably have emptied it right away into an actual trash can.

**Comment by LatvianModder** [comment]
If its in your player file, can you send it here? Gonna need it for testing purposes

**Comment by jinks** [comment]
Sure, no problem.
[jinks_playerfile.zip](https://github.com/LatvianModder/YABBA/files/951700/jinks_playerfile.zip)

It's somewhere in the inventory. Opening up the antibarrel's subtree crashes at least NBTExplorer though. (Or just takes longer than I was willing to wait.)

**Comment by LatvianModder** [comment]
Welp I could not figure out how to fix it / replicate it
