### ISSUE TITLE
Shifting textures from painted to not painted

### ISSUE THREAD

**Issue by coneyaw** [LatvianModder/YABBA#20]
Hey, I'm playing on FTB Beyond and I noticed that your barrels will go blank sometimes. The barrels are painted to look like coal, but sometimes when I look at them, they look like plain oak barrels with no item in the center. I can left or right click them, can't remember which, and the item will show up, but the barrel still looks oak. This appears to be causing a crash with Optifine d7 as well

**Comment by LatvianModder** [comment]
Maybe it's related to this? https://github.com/LatvianModder/YABBA/issues/11#issuecomment-299110111

**Comment by coneyaw** [comment]
Ahhhh sponge, the creator of all bugs (at least a lot of them)

**Comment by LatvianModder** [comment]
Ok, closing as duplicate then
