### ISSUE TITLE
Client crash when rendering Yabba Barrel

### ISSUE THREAD

**Issue by merjilin** [LatvianModder/YABBA#22]
Hey, there!
On the latest update of FTB Beyond, we have encountered an issue where a client crashes upon rendering a yabba barrel. This is the player's crash report: https://gist.github.com/anonymous/7f1f241cca02d9940bd6517e800854d9
and here is our fml-server-latest.log:
https://gist.github.com/merjilin/0752d27547794eeca373b9f456fd1f89
Thank you for your time!

**Comment by OctagonalCeilingFerret** [comment]
This has been happening to members on my FTB Beyond server also.

YABBA-1.10.2-0.5.0
FTB Beyond v 1.6.1 MC 1.10.2

Three people have been experiencing crashes, out of six who play daily on my server. Starting as early as the 11th (The same day we updated from FTB Beyond v1.6.0 (Minecraft version 1.10.2), and YABBA-1.10.2-0.4.3 to current)


Here are some crash reports from my client:

[crash-2017-05-11_23.43.22-client.txt](https://github.com/LatvianModder/YABBA/files/998689/crash-2017-05-11_23.43.22-client.txt)
[crash-2017-05-11_23.48.34-client.txt](https://github.com/LatvianModder/YABBA/files/998690/crash-2017-05-11_23.48.34-client.txt)
[crash-2017-05-13_23.04.35-client.txt](https://github.com/LatvianModder/YABBA/files/998692/crash-2017-05-13_23.04.35-client.txt)
[crash-2017-05-13_23.22.08-client.txt](https://github.com/LatvianModder/YABBA/files/998688/crash-2017-05-13_23.22.08-client.txt)
[crash-2017-05-13_23.42.49-client.txt](https://github.com/LatvianModder/YABBA/files/998691/crash-2017-05-13_23.42.49-client.txt)
[crash-2017-05-14_00.06.08-client.txt](https://github.com/LatvianModder/YABBA/files/998693/crash-2017-05-14_00.06.08-client.txt)
[crash-2017-05-14_00.20.46-client.txt](https://github.com/LatvianModder/YABBA/files/998695/crash-2017-05-14_00.20.46-client.txt)
[crash-2017-05-14_00.28.51-client.txt](https://github.com/LatvianModder/YABBA/files/998696/crash-2017-05-14_00.28.51-client.txt)
[crash-2017-05-14_00.52.26-client.txt](https://github.com/LatvianModder/YABBA/files/998694/crash-2017-05-14_00.52.26-client.txt)
[crash-2017-05-14_01.05.21-client.txt](https://github.com/LatvianModder/YABBA/files/998697/crash-2017-05-14_01.05.21-client.txt)
[crash-2017-05-14_01.21.58-client.txt](https://github.com/LatvianModder/YABBA/files/998698/crash-2017-05-14_01.21.58-client.txt)
[crash-2017-05-14_01.45.03-client.txt](https://github.com/LatvianModder/YABBA/files/998699/crash-2017-05-14_01.45.03-client.txt)
[crash-2017-05-14_01.55.50-client.txt](https://github.com/LatvianModder/YABBA/files/998700/crash-2017-05-14_01.55.50-client.txt)


Here are crash reports from another player:

[crash-2017-05-12_00.08.24-client.txt](https://github.com/LatvianModder/YABBA/files/998676/crash-2017-05-12_00.08.24-client.txt)
[crash-2017-05-12_01.49.12-client.txt](https://github.com/LatvianModder/YABBA/files/998677/crash-2017-05-12_01.49.12-client.txt)
[crash-2017-05-12_02.06.13-client.txt](https://github.com/LatvianModder/YABBA/files/998680/crash-2017-05-12_02.06.13-client.txt)
[crash-2017-05-12_02.11.41-client.txt](https://github.com/LatvianModder/YABBA/files/998681/crash-2017-05-12_02.11.41-client.txt)
[crash-2017-05-12_02.56.35-client.txt](https://github.com/LatvianModder/YABBA/files/998678/crash-2017-05-12_02.56.35-client.txt)
[crash-2017-05-12_22.38.02-client.txt](https://github.com/LatvianModder/YABBA/files/998679/crash-2017-05-12_22.38.02-client.txt)
[crash-2017-05-12_22.42.01-client.txt](https://github.com/LatvianModder/YABBA/files/998683/crash-2017-05-12_22.42.01-client.txt)
[crash-2017-05-12_22.46.00-client.txt](https://github.com/LatvianModder/YABBA/files/998682/crash-2017-05-12_22.46.00-client.txt)
[crash-2017-05-13_23.36.31-client.txt](https://github.com/LatvianModder/YABBA/files/998685/crash-2017-05-13_23.36.31-client.txt)
[crash-2017-05-13_23.48.04-client.txt](https://github.com/LatvianModder/YABBA/files/998684/crash-2017-05-13_23.48.04-client.txt)
[crash-2017-05-14_00.27.29-client.txt](https://github.com/LatvianModder/YABBA/files/998686/crash-2017-05-14_00.27.29-client.txt)
[crash-2017-05-14_01.25.13-client.txt](https://github.com/LatvianModder/YABBA/files/998687/crash-2017-05-14_01.25.13-client.txt)

**Comment by Watchful1** [comment]
I'll add my voice to this one

https://pastebin.com/XBFAYjhp

**Comment by Tydesson** [comment]
I'll also add my voice on this one, with version yabba{1.10.2-0.5.0} [YABBA] (YABBA-1.10.2-0.5.0.jar) 

https://pastebin.com/fLmPqqHu

**Comment by LatvianModder** [comment]
But the latest version for over than a week now is 0.5.1, I belive it was fixed then
