### ISSUE TITLE
YABBA-1.10.2-0.5.1 crashing the game on startup with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by TheVanoq** [LatvianModder/YABBA#24]
Versions:
> Minecraft: 1.10.2
> LWJGL: 2.9.1
> Forge: 1.10.2-12.18.3.2297

Installed mods:
>   ae2stuff-0.6.0.9-mc1.10.2
>   appliedenergistics2-rv4-alpha-11
>   bdlib-1.12.4.24-mc1.10.2
>   FTBLib-1.10.2-3.5.3
>   jei_1.10.2-3.14.7.419
>   QuantumStorage-1.10.2-3.3.4
>   RebornCore-1.10.2-2.13.6.142-universal
>   Waila-1.7.0-B3_1.9.4
>   YABBA-1.10.2-0.5.1

Crash logs:
https://pastebin.com/eHCx3QgG
https://pastebin.com/tHagD7dc

**Comment by TheVanoq** [comment]
Using an older version of YABBA (0.4.0) works just fine in the same configuration.

**Comment by LatvianModder** [comment]
Update FTBLib and add CompatLayer
