### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by phit** [LatvianModder/YABBA#29]
Log https://gist.github.com/phit/aca46cf6229c25b774d2302500928922

Caused by a barrel placed facing upwards, the placing doesn't crash you but when you leave the area and come back you crash.
When placing the barrel some parts of it were also invisible, not sure if this is even an issue on your end or a different mod messing with your rendering code..

**Comment by LatvianModder** [comment]
There are multiple mods missing with the code...
net.fybertech.redstonepaste.CompatibilityTessellator (redstonepaste)
codechicken.lib.render.block.CCBlockRendererDispatcher (CodeChickenLib)

Can you reproduce the issue without these mods?

**Comment by phit** [comment]
So the rendering glitch is also there with just YABBA, JEI and dependencies http://i.imgur.com/Rm5ZQAI.png

After adding Redstone Paste didn't crash, rendering glitch still there though. Then I added CodeChickenLib hoping it would crash, but still nothing.. Not sure what was different in the setup that caused the original crash.
I'll keep trying to reproduce it locally and update if I figure it out.

**Comment by LatvianModder** [comment]
Oh this glitch. I thought I fixed that for 1.11... I [fixed that for 1.12 for sure](http://ss.latmod.com/pc/2017-06-16_15.22.14.png), but I doubt I will backport to 1.11, a lot of code has changed
