### ISSUE TITLE
What are the recipes? No NEI/etc. for MC v1.12 yet!

### ISSUE THREAD

**Issue by Psytrin** [LatvianModder/YABBA#30]
Hiya, I'd like to know how to craft anything for this mod. I cannot find recipes for this mod. Currently there is no NEI/other similar mods to see and search for recipes.

**Comment by LatvianModder** [comment]
What? Have you heard of Just Enough Items, JEI? It has been the new NEI for few years now, since 1.8. Also the recipe book in vanilla will soon show the recipes, if doesn't already
