### ISSUE TITLE
1.12-0.5.2 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [LatvianModder/YABBA#31]
Notes:
     on startup, forge registry

crash report:
https://gist.github.com/2e922fc073728b8f48d0e63e49ebb5ce

fml server latest:
https://gist.github.com/5fe8b76b67106411d91aceff5689726c

**Comment by Protheus** [comment]
Same issue in forge: 2387

**Comment by MokahTGS** [comment]
and 2389.  They need to update to the new Forge recipe system.

Crash log: https://pastebin.com/yyNZYHRG

**Comment by kreezxil** [comment]
tried again on build 2400, same fail.

Issue:  1.12-0.5.2 crashes dedicated server Forge 1.12 build 2400

Notes:
     on startup

crash report:
https://gist.github.com/d54a07e55dfc5c33e81f42a182f60d75

fml server latest:
https://gist.github.com/80c3074c54c55b2f983c33b0bec8066d
