### ISSUE TITLE
1.11.2 - When breaking barrel that contains between 128 and 255 (and many other amounts that I didn't test) items the contents are lost

### ISSUE THREAD

**Issue by Barteks2x** [LatvianModder/YABBA#32]
It probably also happens with some other amounts but I didn't really test it. I tested it only with 1.11.2 version from curse.

Versions I use:
YABBA 1.11.2-0.5.1
FTBLib 1.1x-3.6.5
compatlayer 0.2.9
Forge 1.11.2-13.20.0.2345

**Comment by Barteks2x** [comment]
This may actually be the same as #28 but I found some pattern in when the items are lost. In all of my testing they did disappear when there are 128-255 items, and never when there are less. But they also disappear when there are much more items inside.

**Comment by Bass2style** [comment]
confirmed here, lost much of stuff with this issue, but on 1.12 version of the mod. (0.5.3 for 1.12, present in the FTB Unstable modpack), i cannot move my base due to risk of item lost. :( i need to transfer to another mod equivalence before. :/

**Comment by davqvist** [comment]
MC 1.12.1
Forge 2446
YABBA 0.5.3

I encountered same problem. To replicate: Fill a barrel to its max (64 stacks), add a void upgrade, break with an axe, the items are gone, the void upgrade still in there, you can't put anything in there now because they are voided as well.
