### ISSUE TITLE
[1.12][0.5.3] Barrel item model is a bit broken

### ISSUE THREAD

**Issue by starg09** [LatvianModder/YABBA#33]
On forge build 2400, mod version 0.5.3; the barrel shows incorrectly in the inventory, renders as a full-size block in its item form.

[Gfy of what's going on.](https://gfycat.com/BowedLoneFulmar)

**Comment by Bass2style** [comment]
this bug happens also in 1.12 version of Yabba, (also 0.5.3). (FTB Unstable 1.12), but not everytime.
