### ISSUE TITLE
Refined Storage External Storage + Yabba Barrel = Weird capacity displayed.

### ISSUE THREAD

**Issue by llloyd4** [LatvianModder/YABBA#35]
Ok, so, I put an external storage bus on some of my Yabba barrels so the RS network would have access to the contents of those barrels and the capacity displayed oddly, something like 254 / 64 @ over 300% or something like that. So there seems to be a compatibility issue between the two mods. I've updated RS to the latest and already using the latest Yabba. 

http://i15.photobucket.com/albums/a395/llloyd4/2017-08-08_01.12.37_zpsflmjtzax.png

https://github.com/raoulvdberge/refinedstorage/issues/1409

(In case your wondering, I have had compatibility issues boiled down to both mod authors blaming the other so... )

**Comment by LatvianModder** [comment]
Nah, this one is on me

**Comment by raoulvdberge** [comment]
RS counts the amount of slots * 64, for that display.

**Comment by llloyd4** [comment]
So you are saying, and remember I am not a coder so take this with a grain of salt, that Yabba changes the slot maximum amount where, say, Drawers adds slots but limits what can go in to one item?

**Comment by raoulvdberge** [comment]
The calculation RS does is a bit flaky since it doesn't count unstackable items or slot max amounts.

**Comment by mgdgfbhevdyeh** [comment]
AE,RFTOOLS,ENDERIO have same isseus.

**Comment by sdrush** [comment]
I'm not sure if this is related to the above or not, but I am having a weird issue with AE2 storage buses as well as Refined Storage External Storage with the Anti-barrel.  At first it was crashing my AE2 system forcing me to restart the server to recover any time I attempted to withdraw certain items that were being stored in the anti-barrel.  I hooked the same barrel up to a small RS system with an External Storage, and the item counts are showing as negative and I am unable to remove any of the items with negative item counts.  The items with negative counts include some vanilla items like gold horse armor, as well as RS stack and speed upgrades and empty RS 64k drives, and forestry bees.  I also tried piping the items out into a chest with some enderio item conduits, but that doesnt work either.

**Comment by LatvianModder** [comment]
I thought it uses `IDeepStorageUnit` whenever the TileEntity extends that. Should it use it's `getMaxStoredCount()`?

**Comment by raoulvdberge** [comment]
IDeepStorageUnit has been deprecated for the StorageDrawers API (IItemRepository).

**Comment by LatvianModder** [comment]
Wait how I implement those IItemRepository methods without a hard dependency on storagedrawers?

**Comment by LatvianModder** [comment]
Eh, screw IItemRepository, I will just make Refined Storage integration. It's the only storage mod I personally use anyway

**Comment by llloyd4** [comment]
It's the superior one so... :D

**Comment by LatvianModder** [comment]
Fixed in 4.1.1. Didn't integrate with RS, instead made an IItemHandler that does very well. Tested a lot with External Storage

**Comment by raoulvdberge** [comment]
Oh, a nice IItemHandler would work good as well obviously :)

**Comment by LatvianModder** [comment]
Quick discovery - Refined Storage does **not** like 700'000'000 items in the barrel.. so I guess I will have to figure out how to do Refined Storage integration after all. Tested with 70'000 and that seems fine. Normally you don't get much more than that

**Comment by llloyd4** [comment]
Really? Never noticed I've had Storage Drawers with 6 emerald upgrades and
no issues. O.o

**Comment by LatvianModder** [comment]
Because Refined Storage integrates with Storage Drawers. Maybe if I made an API, RS would integrate with Yabba too <.<

**Comment by raoulvdberge** [comment]
Well, if you expose 700 mil slots to RS, it will scan every tick every slot to see if there are changes to process for the storage cache. So a special integration might be a cool thing indeed (you can do so by implementing a IStorageProvider on the tile I believe)

**Comment by llloyd4** [comment]
700 *million* slots? O.o Holy...

**Comment by LatvianModder** [comment]
You need to update your API brah. IStorage still has @Nullable ItemStacks

**Comment by raoulvdberge** [comment]
Now that I think about it, you probably want external storage to read your inv right? That isn't possible yet with the current API... you could use IStorageProvider but then you would just need to connect an RS cable to the barrel and it would work.. That can't be a thing... I will look into it.
