### ISSUE TITLE
Issues with Yabba and Storage Bus from Applied Energistics 2.

### ISSUE THREAD

**Issue by cap1o** [LatvianModder/YABBA#36]
Hello, 

Actually, we discuss on Github from AE2 about an issues with Yabba and Storage Bus from AE2.
May could you have a look and if you have a idea to fix it.
Resume of the issue : 

> Hello !
> 
> I dunno if it's a bug or not but i have set up Yabba mod Barrels with storage bus to my ME systeme and then items already on the ME syteme won't to be added inside the barrel.
> 
> Exemple : I have got a yabba barrel lock to accept blaze rod is empty. I connect a this to my ME systeme with a storage bus and it still empty.
> I have 250 blaze rod on my systeme and nothing on the barrel.
> @cap1o

So, what do you think ? Can you have a hand by your side ? Or it's only from AE2 mod ?

Here the link to AE2 threat : [https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3021#issuecomment-321960526](url)

Thank you for attention.
**Cap1o**

**Comment by Sadumon** [comment]
This is standard AE2 behavior, and nothing that YABBA can control.  Even if you set a higher priority on the storage bus than where the items already are, the items will not automatically move.  If you remove the items from the AE system and then add them back, it will put them into the barrel.  Additionally, any new items will move into the barrel.  To move existing items into the barrel, the easiest way is to have an export bus pointing right back into an AE interface, and just have it export the item you wish to place into the barrel.  Let it run for a little while and eventually all of that item will be in the barrel.

**Comment by cap1o** [comment]
IIt's done already i have setup both on Yabba barrels, storage by one side and export to the other side too.
thank you !
