### ISSUE TITLE
Dupe bug with tinkers construct

### ISSUE THREAD

**Issue by jwebba** [LatvianModder/YABBA#38]
Placing a barrel next to a Tinkers Crafting Station will allow you to dupe anything. The blocks interact in a strange way. Opening up the GUI in the crafting station and having the item you want to dupe in the barrel. You can shift click the item (in craft station) and it will produce several stacks of the item completely filling your inventory. Some of these are ghost items that disappear others are the duplicated versions.  

Also inb4 the just add it to the # Blacklist of TE classnames doing so will crash the client completely to desktop. 

Description: Updating screen events

java.lang.StackOverflowError: Updating screen events
	at com.latmod.yabba.util.Barrel.getFlag(Barrel.java:96)
	at com.latmod.yabba.util.Barrel.extractItem(Barrel.java:193)
	at net.minecraftforge.items.SlotItemHandler.func_82869_a(SlotItemHandler.java:120)
	at slimeknights.mantle.inventory.SlotWrapper.func_82869_a(SlotWrapper.java:43)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:248)
	at slimeknights.mantle.inventory.ContainerMultiModule.func_184996_a(ContainerMultiModule.java:120)
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267)

    # Blacklist of TE classnames for the crafting station to connect to. Mainly for compatibility.
    S:craftingStationBlacklist <
        de.ellpeck.actuallyadditions.mod.tile.TileEntityItemViewer
		yabba:barrel.withTag({Barrel: {Tier: "wood", Model: "barrel", Skin: "minecraft_planks_0", Flags: 0, Count: 0}})
		yabba:barrel
		latmod.yabba.block.BlockItemBarrel
		latmod.yabba.tile.TileItemBarrel
     >

**Comment by simox66** [comment]
Why this config doesn't workshop in my server?

**Comment by LatvianModder** [comment]
```yabba:barrel.withTag({Barrel: {Tier: "wood", Model: "barrel", Skin: "minecraft_planks_0", Flags: 0, Count: 0}})
yabba:barrel
latmod.yabba.block.BlockItemBarrel
latmod.yabba.tile.TileItemBarrel```
none of these are classnames. For latest public version, this is: `com.latmod.yabba.tile.TileBarrel`

**Comment by jwebba** [comment]
Gave it a go looks like it worked. Thanks.

**Comment by simox66** [comment]
sorry, I have forgotten to answer you, creates a glitch with the inventory that doesn'tt allow duplicate

**Comment by LatvianModder** [comment]
(As of 1.0.0 the tile ID class is `com.latmod.yabba.tile.TileItemBarrel`)
