### ISSUE TITLE
Nonstackable-Item Duplication (w/ Tinkers' Construct)

### ISSUE THREAD

**Issue by Shamrock-Frost** [LatvianModder/YABBA#42]
If you place a barrel and put 3+ of any nonstackable item (e.g. Leather Boots) in it, then place a Crafting Station next to the barrel, you can duplicate the contents of the barrel by picking it up twice.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/YABBA/issues/38

**Comment by Shamrock-Frost** [comment]
Crap, I thought I looked at the closed issues but I guess I missed that one. Do you have any idea why this is happening?
