### ISSUE TITLE
Warning Message for lastest verison

### ISSUE THREAD

**Issue by masternetra** [LatvianModder/YABBA#49]
Got this from log: `[16:21:54] [main/WARN]: Unable to resolve texture due to upward reference: #tex in yabba:models/item/upgrade_base.json`

**Comment by LatvianModder** [comment]
Hasn't it always been there? I think its a bug I can't fix, because I'm not doing anything wrong

**Comment by masternetra** [comment]
I dunno, this is the first version of the mod I've tried.
