### ISSUE TITLE
Crash after pickup a cobblestone with a barrel in hotbar.

### ISSUE THREAD

**Issue by Blatts12** [LatvianModder/YABBA#55]
Upgrades on a barrel - tier iron, gold, diamond and pickup.

https://pastebin.com/kdQzk7pX

**Comment by LatvianModder** [comment]
Caused by newer forge verision. Welp

**Comment by ClaudiusMinimus** [comment]
What version of Forge does Yabba support?

**Comment by LatvianModder** [comment]
I think `14.23.1.2556` still worked. The [changelog](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2607/forge-1.12.2-14.23.1.2607-changelog.txt) says
```Build 1.12.2-14.23.1.2558:
	LexManos: Re-enable Vanilla's Shapeless recipe matching.
	LexManos: Restore binary compatibility in EntityItemPickupEvent```
but I guess that's not true for Yabba

**Comment by ClaudiusMinimus** [comment]
Thank you. Any updates coming soon?

**Comment by LatvianModder** [comment]
Holding back updates for now, because Im doing large rewrites in all mods

**Comment by Rred26** [comment]
I had this crash as well when I had a YABBA barrel (with the pick-up upgrade and 1 cobblestone inside) in my inventory. I tried to walk over a cobblestone item drop in the world when the crash occurred.

I'm running:
FTB Revolution v1.3
YABBA v1.0.11
Forge v14.32.1.2587
Minecraft v1.12.2

Here's the crash log:
[crash-2018-02-04_23.05.17-server.txt](https://github.com/LatvianModder/YABBA/files/1694145/crash-2018-02-04_23.05.17-server.txt)

Hope this helps.
