### ISSUE TITLE
Yabba Antibarrel

### ISSUE THREAD

**Issue by berni1212** [LatvianModder/YABBA#56]
FTB Revelation Modpack version 1.3.0  Minecraft version 1.12.2

Issue : the Anti barrels gives uses around it a Disconnect from the server with following message 

https://i.imgur.com/VPXhsWe.png

No crash log or Crash file Providen 

Barrel content 8000 Stone swords and other items Nonstackable 

NBT data got too big for the Server to handle and it kicks People around it or if they have it in their inventory !

**Comment by LatvianModder** [comment]
oh geez. Yeah, I already had plans for compressing data a lot

**Comment by berni1212** [comment]
Well we found that out after i removed a Whole base to finde it ^^ they weren't that happy about it until we found out what was  causing it when he had it in his inventory and he got that message when other people around him were fine :D

**Comment by Archaon-Zero** [comment]
Same issue. At first I thought it was the nether star barrel with the 5M wooden planks, but it proved to be the anti-barrel connected to my Applied energistics 2 system. It had 1583 entries on NBTexplorer and deleting it solved the crash. Things came to a head when I started disenchanting loads of gold swords, while placing the resulting books back in the barrel. ;)

**Comment by PantACRO4life** [comment]
Same here nbtexplorer fix it but nothing else go do other than voiding over stuff but here keep happening cause we forgot to void new stuff that came in so it's anoying

**Comment by LatvianModder** [comment]
Try newest version from http://maven.latmod.com. Just dont forget to update FTBLib [and FTBUtilities] too
