### ISSUE TITLE
Suggestion: Have "Display Bar" and "Always Display Data" as global options

### ISSUE THREAD

**Issue by Undeadbanana** [LatvianModder/YABBA#57]
If anyone wants to take a look at their massive storage to see which items are near capacity, it's kind of a pain to have to sneak around and hover over everything. Even worse is having to sneak right click hundreds of barrels just to turn the options on. I think you should have those two options (Display Bar and Always Display Data) as global options, with the options in the barrels acting as overrides for individual barrels.

Also, I think you should have an item for locking barrels from outside the gui.

**Comment by LatvianModder** [comment]
But.. they are... `Inventory > Client Config (Gear icon) > Yabba`

**Comment by Undeadbanana** [comment]
Yeah, found it eventually. 

I think your mod is absolutely great; the only thing storage drawers has over you is the way locked chests work. Empty locked chests don't accept items and chests can be locked from outside a GUI using a key. Your mod offers a lot of better decorating options without the need of looking for a certain tree type and it's not limited to just wooden barrels/shapes. Love it! Thanks for making it.
