### ISSUE TITLE
Images gone from CurseForge page and Wiki link 404s

### ISSUE THREAD

**Issue by MauveCloud** [LatvianModder/YABBA#59]
This isn't exactly a bug in the mod itself, but since comments aren't enabled on the Curse/CurseForge page for the mod, I'm not sure of a better way to contact the author about this.

The description page has two images that presumably are supposed to show off the mod, but currently they show imgur.com placeholder images that say "The image you are requesting does not exist or is no longer available."  I have a vague memory that the images worked a month or two ago.  Also, the link for the Wiki gives me Error 404 (page not found).

**Comment by LatvianModder** [comment]
Uh oh. I deleted all my imgur images. Woops!

**Comment by LatvianModder** [comment]
Fixed
