### ISSUE TITLE
Crash if Collect Pickup Upgrade is in inventory 1.12.2

### ISSUE THREAD

**Issue by ClaudiusMinimus** [LatvianModder/YABBA#60]
I am new to Yabba and want to include it in my upcoming modpack, but in testing if the Collect Pickup Upgrade has been applied to a barrel then if I drop anything, MC crashes. So far it only happens when I use a barrel with this upgrade.

Below is the crash report
Thank you,
CM

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  SoundFixPatchingLoader (AmbientSounds v2.2.2 mc1.12.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  CorePlugin (ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  CreativePatchingLoader (CreativeCore v1.9.16 mc1.12.2.jar)
  LoadingPlugin (AdChimneys-1.12.1-3.2.1.2-build.0079.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LittlePatchingLoader (LittleTiles v1.5.0-pre67 mc1.12.2.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  BCModPlugin (backpacks 1.12.2 - 3.4.3.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 1/30/18 6:02 PM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/entity/item/EntityItem;)V
	at com.latmod.yabba.YabbaEventHandler.onItemPickup(YabbaEventHandler.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1060_YabbaEventHandler_onItemPickup_EntityItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:478)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:396)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.latmod.yabba.YabbaEventHandler.onItemPickup(YabbaEventHandler.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1060_YabbaEventHandler_onItemPickup_EntityItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:478)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:396)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 6790
	Entity Name: ClaudiusMinimus
	Entity's Exact location: 232.64, 12.00, 271.53
	Entity's Block location: World: (232,12,271), Chunk: (at 8,0,15 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@9c5141e
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 941431936 bytes (897 MB) / 4782555136 bytes (4561 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7168m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2607 148 mods loaded, 148 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                    | Version                  | Source                                               | Signature                                |
	|:--------- |:------------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                             | 1.12.2                   | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | mcp                                   | 9.42                     | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | FML                                   | 8.0.99.99                | forge-1.12.2-14.23.1.2607.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                 | 14.23.1.2607             | forge-1.12.2-14.23.1.2607.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy                     | 1.0.0                    | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | ivtoolkit                             | 1.3.3-1.12               | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | littletilescore                       | 1.0.0                    | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | actuallyadditions                     | 1.12.2-r129              | ActuallyAdditions-1.12.2-r129.jar                    | None                                     |
	| UCHIJAAAA | baubles                               | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
	| UCHIJAAAA | actuallybaubles                       | 1.1                      | ActuallyBaubles-1.12-1.1.jar                         | None                                     |
	| UCHIJAAAA | ambientsounds                         | 2.0.0                    | AmbientSounds v2.2.2 mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | ctm                                   | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                              | None                                     |
	| UCHIJAAAA | chisel                                | MC1.12-0.1.1.26          | Chisel-MC1.12-0.1.1.26.jar                           | None                                     |
	| UCHIJAAAA | jei                                   | 4.8.5.138                | jei_1.12.2-4.8.5.138.jar                             | None                                     |
	| UCHIJAAAA | mantle                                | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                             | None                                     |
	| UCHIJAAAA | tconstruct                            | 1.12.2-2.9.0.55          | TConstruct-1.12.2-2.9.0.55.jar                       | None                                     |
	| UCHIJAAAA | extrautils2                           | 1.0                      | extrautils2-1.12-1.7.3.jar                           | None                                     |
	| UCHIJAAAA | flyringbaublemod                      | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar          | None                                     |
	| UCHIJAAAA | theoneprobe                           | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                          | None                                     |
	| UCHIJAAAA | immersiveengineering                  | 0.12-76                  | ImmersiveEngineering-0.12-76.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | natura                                | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                           | None                                     |
	| UCHIJAAAA | betterwithmods                        | ${version}               | BetterWithMods-1.12-2.0.25.jar                       | None                                     |
	| UCHIJAAAA | appleskin                             | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| UCHIJAAAA | appliedenergistics2                   | rv5-stable-7             | appliedenergistics2-rv5-stable-7.jar                 | None                                     |
	| UCHIJAAAA | architect                             | 1.2.0.6                  | Architect-MC1.12-1.2.0.6.jar                         | None                                     |
	| UCHIJAAAA | thedragonlib                          | 1.12.2-5.2.0             | thedragonlib-1.12.2-5.2.0.jar                        | None                                     |
	| UCHIJAAAA | armorplus                             | 1.12.2-11.10.1.35-beta   | armorplus-1.12.2-11.10.1.35-beta.jar                 | None                                     |
	| UCHIJAAAA | aroma1997core                         | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aroma1997sdimension                   | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar    | None                                     |
	| UCHIJAAAA | aromabackup                           | 2.1.1.3                  | AromaBackup-1.12.2-2.1.1.3.jar                       | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aromabackuprecovery                   | 2.1.1.3                  | AromaBackup-1.12.2-2.1.1.3.jar                       | None                                     |
	| UCHIJAAAA | morphtool                             | 1.2-16                   | Morph-o-Tool-1.2-16.jar                              | None                                     |
	| UCHIJAAAA | quark                                 | r1.4-122                 | Quark-r1.4-122.jar                                   | None                                     |
	| UCHIJAAAA | autoreglib                            | 1.3-15                   | AutoRegLib-1.3-15.jar                                | None                                     |
	| UCHIJAAAA | backpacks16840                        | 3.4.3                    | backpacks 1.12.2 - 3.4.3.jar                         | None                                     |
	| UCHIJAAAA | badwithernocookiereloaded             | 1.12.2-2.12              | badwithernocookiereloaded-1.12.2-2.12.jar            | None                                     |
	| UCHIJAAAA | bedbugs                               | @VERSION@                | BedBugs-1.12-1.0.1.jar                               | None                                     |
	| UCHIJAAAA | betterbuilderswands                   | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar      | None                                     |
	| UCHIJAAAA | bibliocraft                           | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                    | None                                     |
	| UCHIJAAAA | biomesoplenty                         | 7.0.1.2302               | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar        | None                                     |
	| UCHIJAAAA | bloodmoon                             | 1.5.2                    | Bloodmoon-MC1.12.2-1.5.2.jar                         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | bookshelf                             | 2.3.523                  | Bookshelf-1.12.2-2.3.523.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | botania                               | r1.10-353                | Botania r1.10-353.jar                                | None                                     |
	| UCHIJAAAA | chameleon                             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| UCHIJAAAA | chesttransporter                      | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                    | None                                     |
	| UCHIJAAAA | chiselsandbits                        | 14.11                    | chiselsandbits-14.11.jar                             | None                                     |
	| UCHIJAAAA | codechickenlib                        | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | controlling                           | 3.0.6                    | Controlling-3.0.6.jar                                | None                                     |
	| UCHIJAAAA | crafttweaker                          | 4.1.0                    | CraftTweaker2-1.12-4.1.0.jar                         | None                                     |
	| UCHIJAAAA | cookingforblockheads                  | 6.3.17                   | CookingForBlockheads_1.12.1-6.3.17.jar               | None                                     |
	| UCHIJAAAA | corail_pillar_extension_biomesoplenty | 4.0.1                    | corail_pillar_extension_biomesoplenty-4.0.1-1.12.jar | None                                     |
	| UCHIJAAAA | corail_pillar_extension_chisel        | 4.0.0                    | corail_pillar_extension_chisel-4.0.0-1.12.jar        | None                                     |
	| UCHIJAAAA | ic2                                   | 2.8.16-ex112             | industrialcraft-2-2.8.16-ex112.jar                   | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | forestry                              | 5.7.0.238                | forestry_1.12.2-5.7.0.238.jar                        | None                                     |
	| UCHIJAAAA | corail_pillar_extension_forestry      | 4.0.0                    | corail_pillar_extension_forestry-4.0.0-1.12.jar      | None                                     |
	| UCHIJAAAA | corail_pillar_extension_quark         | 4.0.0                    | corail_pillar_extension_quark-4.0.0-1.12.jar         | None                                     |
	| UCHIJAAAA | craftingtweaks                        | 8.1.6                    | CraftingTweaks_1.12.1-8.1.6.jar                      | None                                     |
	| UCHIJAAAA | ctgui                                 | 1.0.0                    | CraftTweaker2-1.12-4.1.0.jar                         | None                                     |
	| UCHIJAAAA | crafttweakerjei                       | 2.0.0                    | CraftTweaker2-1.12-4.1.0.jar                         | None                                     |
	| UCHIJAAAA | creativecore                          | 1.9.9                    | CreativeCore v1.9.16 mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | customspawner                         | 3.11.3                   | CustomMobSpawner-3.11.3.jar                          | None                                     |
	| UCHIJAAAA | customnpcs                            | 1.12                     | CustomNPCs_1.12.2(20jan18).jar                       | None                                     |
	| UCHIJAAAA | darkutils                             | 1.8.192                  | DarkUtils-1.12.2-1.8.192.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | journeymap                            | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                          | None                                     |
	| UCHIJAAAA | defaultoptions                        | 9.2.5                    | DefaultOptions_1.12.2-9.2.5.jar                      | None                                     |
	| UCHIJAAAA | mocreatures                           | 12.0.3                   | DrZharks MoCreatures Mod-12.0.3.jar                  | None                                     |
	| UCHIJAAAA | earthworks                            | 1.3.4.3                  | Earthworks-1.12-1.3.6.jar                            | None                                     |
	| UCHIJAAAA | elevatorid                            | 1.3.5                    | ElevatorMod-1.12.2-1.3.5.jar                         | None                                     |
	| UCHIJAAAA | ichunutil                             | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                           | None                                     |
	| UCHIJAAAA | mcmultipart                           | 2.4.1                    | MCMultiPart-2.4.1.jar                                | None                                     |
	| UCHIJAAAA | ftbl                                  | 4.2.5                    | FTBLib-4.2.5.jar                                     | None                                     |
	| UCHIJAAAA | shetiphiancore                        | 3.5.6                    | shetiphiancore-1.12.0-3.5.6.jar                      | None                                     |
	| UCHIJAAAA | endertanks                            | 1.6.3                    | endertanks-1.12.0-1.6.3.jar                          | None                                     |
	| UCHIJAAAA | valkyrielib                           | 1.12.2-2.0.6b            | valkyrielib-1.12.2-2.0.7a.jar                        | None                                     |
	| UCHIJAAAA | environmentaltech                     | 1.12.2-2.0.7b            | environmentaltech-1.12.2-2.0.7b.jar                  | None                                     |
	| UCHIJAAAA | flatcoloredblocks                     | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar                     | None                                     |
	| UCHIJAAAA | foamfix                               | @VERSION@                | foamfix-0.7.3-1.12-law.jar                           | None                                     |
	| UCHIJAAAA | forgeendertech                        | 1.12.1-4.3.1.0           | ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar         | None                                     |
	| UCHIJAAAA | forgelin                              | 1.6.0                    | Forgelin-1.6.0.jar                                   | None                                     |
	| UCHIJAAAA | ftbu                                  | 4.2.4                    | FTBUtilities-4.2.4.jar                               | None                                     |
	| UCHIJAAAA | fw                                    | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar                    | None                                     |
	| UCHIJAAAA | limelib                               | 1.7.9                    | limelib-1.12.2-1.7.9.jar                             | None                                     |
	| UCHIJAAAA | furnus                                | 2.1.5                    | furnus-1.12.2-2.1.5.jar                              | None                                     |
	| UCHIJAAAA | gravestone                            | 1.0.13                   | GraveStone-1.12-Graves-1.0.13.jar                    | None                                     |
	| UCHIJAAAA | gravestone-extended                   | 1.2.6                    | GraveStone-1.12.2-Extended-1.2.6.jar                 | None                                     |
	| UCHIJAAAA | incontrol                             | 3.6.6                    | incontrol-1.12-3.6.6.jar                             | None                                     |
	| UCHIJAAAA | inventorytweaks                       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest                             | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                      | None                                     |
	| UCHIJAAAA | jeiintegration                        | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar                   | None                                     |
	| UCHIJAAAA | joypadsplitscreenmod                  | 1.12.0-0.22              | JoypadMod-1.12-14.21.0.2322.jar                      | None                                     |
	| UCHIJAAAA | jeresources                           | 0.8.6.28                 | JustEnoughResources-1.12.2-0.8.6.28.jar              | None                                     |
	| UCHIJAAAA | keywizard                             | 1.10.2-1.5               | keywizard-1.12.2-1.5.2.jar                           | None                                     |
	| UCHIJAAAA | littletiles                           | 1.5.0                    | LittleTiles v1.5.0-pre67 mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | llor                                  | 1.1.4-mc1.12             | LLOverlayReloaded-1.1.4-mc1.12.jar                   | None                                     |
	| UCHIJAAAA | mtrm                                  | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar           | None                                     |
	| UCHIJAAAA | mobdismemberment                      | 7.0.0                    | MobDismemberment-1.12.2-7.0.0.jar                    | None                                     |
	| UCHIJAAAA | mobends                               | 0.24                     | mobends-0.24_for_MC-1.12.jar                         | None                                     |
	| UCHIJAAAA | mob_grinding_utils                    | 0.3.4                    | MobGrindingUtils-0.3.4.jar                           | None                                     |
	| UCHIJAAAA | modnametooltip                        | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                     | None                                     |
	| UCHIJAAAA | moreoverlays                          | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                       | None                                     |
	| UCHIJAAAA | moreplayermodels                      | 1.12.2                   | MorePlayerModels_1.12.2(18jan18).jar                 | None                                     |
	| UCHIJAAAA | morpheus                              | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                              | None                                     |
	| UCHIJAAAA | mousetweaks                           | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                         | None                                     |
	| UCHIJAAAA | mputils                               | 1.4.1                    | MPUtils-1.12-1.4.1.jar                               | None                                     |
	| UCHIJAAAA | mpbasic                               | 1.3.0                    | mpbasic-1.12-1.3.0.jar                               | None                                     |
	| UCHIJAAAA | multistorage                          | 1.4.7                    | multistorage-1.12.0-1.4.7.jar                        | None                                     |
	| UCHIJAAAA | naturescompass                        | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                      | None                                     |
	| UCHIJAAAA | netherportalfix                       | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar                    | None                                     |
	| UCHIJAAAA | nmsot                                 | 1.2.1-mc1.12             | NoMobSpawningOnTrees-1.2.1-mc1.12.jar                | None                                     |
	| UCHIJAAAA | recipehandler                         | 0.9                      | NoMoreRecipeConflict-0.9(1.12).jar                   | None                                     |
	| UCHIJAAAA | notenoughscaffold                     | 1.4                      | NotEnoughScaffold-1.12.2-1.4.jar                     | None                                     |
	| UCHIJAAAA | notenoughwands                        | 1.6.1                    | notenoughwands-1.12-1.6.1.jar                        | None                                     |
	| UCHIJAAAA | opframe                               | 1.4.0                    | OnlinePicFrame v1.4.15 mc1.12.2.jar                  | None                                     |
	| UCHIJAAAA | openglider                            | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar                          | None                                     |
	| UCHIJAAAA | guilib                                | $version                 | paintingselgui-PSG Revamed-1.12.2-1.1.0.1.jar        | None                                     |
	| UCHIJAAAA | paintingselgui                        | $version                 | paintingselgui-PSG Revamed-1.12.2-1.1.0.1.jar        | None                                     |
	| UCHIJAAAA | clayspawn                             | 1.12a                    | Pam's ClaySpawn 1.12a.jar                            | None                                     |
	| UCHIJAAAA | getalltheseeds                        | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar                   | None                                     |
	| UCHIJAAAA | harvestcraft                          | 1.12.2m                  | Pam's HarvestCraft 1.12.2m.jar                       | None                                     |
	| UCHIJAAAA | reborncore                            | 3.6.5.197                | RebornCore-1.12.2-3.6.5.197-universal.jar            | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | quantumstorage                        | 4.4.6                    | QuantumStorage-1.12-4.4.6.jar                        | None                                     |
	| UCHIJAAAA | quickleafdecay                        | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                    | None                                     |
	| UCHIJAAAA | rangedpumps                           | 0.5                      | rangedpumps-0.5.jar                                  | None                                     |
	| UCHIJAAAA | reauth                                | 3.5.2                    | ReAuth-3.5.2.jar                                     | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCHIJAAAA | reccomplex                            | 1.4.7                    | RecurrentComplex-1.4.7.jar                           | None                                     |
	| UCHIJAAAA | resourceloader                        | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | roguelike                             | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                   | None                                     |
	| UCHIJAAAA | rtfm                                  | 1.0.0.1                  | RTFM-MC1.12-1.0.0.1.jar                              | None                                     |
	| UCHIJAAAA | rustic                                | 0.4.8                    | rustic-0.4.8.jar                                     | None                                     |
	| UCHIJAAAA | signedit                              | 1.12.2-4                 | signedit-1.12.2-5.jar                                | None                                     |
	| UCHIJAAAA | simplevoidworld                       | 1.2.0.9                  | Simple-Void-World-1.12-1.2.0.9-universal.jar         | None                                     |
	| UCHIJAAAA | sophisticatedwolves                   | 3.12.0                   | SophisticatedWolves-1.12.2-3.12.0.jar                | None                                     |
	| UCHIJAAAA | soulshardstow                         | 1.12-2.7.4-53            | SoulShards-TOW-1.12-2.7.4-53.jar                     | None                                     |
	| UCHIJAAAA | stevescarts                           | ${version}               | StevesCarts-1.12.2-2.4.16.81.jar                     | None                                     |
	| UCHIJAAAA | storagedrawers                        | 1.12-5.2.5               | StorageDrawers-1.12.2-5.3.4.jar                      | None                                     |
	| UCHIJAAAA | tinkertoolleveling                    | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar                    | None                                     |
	| UCHIJAAAA | topaddons                             | 1.12.2-1.3.0             | topaddons-1.12.2-1.3.0.jar                           | None                                     |
	| UCHIJAAAA | torchmaster                           | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar                      | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJAAAA | torohealthmod                         | 1.12.2-11                | torohealth-1.12.2-11.jar                             | None                                     |
	| UCHIJAAAA | trackapi                              | 1.0                      | TrackAPI-1.0_1.12.jar                                | None                                     |
	| UCHIJAAAA | twilightforest                        | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar          | None                                     |
	| UCHIJAAAA | usefulnullifiers                      | 1.4.1                    | usefulnullifiers-1.4.1.jar                           | None                                     |
	| UCHIJAAAA | waterstrainer                         | 3.2.0                    | WaterStrainer-1.12-3.2.0.jar                         | None                                     |
	| UCHIJAAAA | waystones                             | 4.0.20                   | Waystones_1.12.2-4.0.20.jar                          | None                                     |
	| UCHIJAAAA | xpbook                                | 0.0.3-beta               | xpbook-1.12-0.0.3-beta.jar                           | None                                     |
	| UCHIJAAAA | yabba                                 | 1.0.11                   | YABBA-1.0.11.jar                                     | None                                     |
	| UCHIJAAAA | adchimneys                            | 1.12.1-3.2.1.2           | AdChimneys-1.12.1-3.2.1.2-build.0079.jar             | None                                     |
	| UCHIJAAAA | corail_pillar                         | 4.1.0                    | corail_pillar-4.1.0-1.12.jar                         | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SoundFixPatchingLoader (AmbientSounds v2.2.2 mc1.12.2.jar)
  com.creativemd.ambientsounds.soundfix.SoundFixTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
CorePlugin (ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CreativePatchingLoader (CreativeCore v1.9.16 mc1.12.2.jar)
  
LoadingPlugin (AdChimneys-1.12.1-3.2.1.2-build.0079.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LittlePatchingLoader (LittleTiles v1.5.0-pre67 mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
BCModPlugin (backpacks 1.12.2 - 3.4.3.jar)
  brad16840.core.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	AE2 Version: stable rv5-stable-7 for Forge 14.23.1.2554
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.6.5.197
		Runtime Debofucsation 1
		RenderEngine: 0
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ClaudiusMinimus'/6790, l='Botania Tech', x=232.64, y=12.00, z=271.53]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/YABBA/issues/55
