### ISSUE TITLE
Crash with Collect Pickups upgrade

### ISSUE THREAD

**Issue by Lethann** [LatvianModder/YABBA#62]
FTB Revelations 1.4.0 (Single Player, Creative)
YABBA 1.0.11

I was testing all the Yabba functionalities in a creative sandbox (The wiki/web guide results in an Error page) and I was testing a barrel with the Collect Pickups upgrade when it started crashing my game when trying to pickup items. 

Steps:

1) Made a barrel
2) Throw some cobblestone in it
3) Apply the Collect Pickup upgrade
4) Pickup barrel and have it in inventory.
5) throw some cobble on the ground
6) run over cobble
7) Game crash (see attached crash report)

[crash-2018-02-21_21.06.17-server.txt](https://github.com/LatvianModder/YABBA/files/1746514/crash-2018-02-21_21.06.17-server.txt)

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/YABBA/issues/55
