### ISSUE TITLE
Crashing on start up in MC 1.10

### ISSUE THREAD

**Issue by kyoseal** [LatvianModder/YABBA#63]
Hi,

I got this error but have both compat layer and the most up to date FTBlib installed so am unsure of the problem. I've tried with multiple versions of Compat layer, FTBlib and YABBA Any help would be appreciated.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.11.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  PlusTiC (plustic-5.2.1.3.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  BedPatch (bedpatch-2.2-1.10.2.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.14.137-universal.jar)
  BaseMetals (BaseMetals-1.10.2-2.5.0-beta4.238.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  AstralCore (astralsorcery-1.4.5.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  Plugin (NotEnoughIDs-1.5.3.1.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.2.5a.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 2/24/18 7:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from YABBA (yabba)
Caused by: java.lang.NoClassDefFoundError: com/latmod/yabba/block/BlockBarrel
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:71)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:593)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.latmod.yabba.block.BlockBarrel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: com/latmod/yabba/block/BlockBarrelBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: com.latmod.yabba.block.BlockBarrelBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 413175696 bytes (394 MB) / 2102394880 bytes (2005 MB) up to 5592580096 bytes (5333 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6000m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 175 mods loaded, 175 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UC	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UC	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UC	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UC	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UC	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UC	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UC	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UC	actuallybaubles{1.1.1} [Actually Baubles] (ActuallyBaubles-1.10.2-1.1.1.jar) 
	UC	libVulpes{0.2.6.} [libVulpes] (LibVulpes-1.10.2-0.2.6-universal.jar) 
	UC	advancedRocketry{1.2.5a} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.2.5a.jar) 
	UC	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UC	bdlib{1.12.4.25} [BD Lib] (bdlib-1.12.4.25-mc1.10.2.jar) 
	UC	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	UC	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UC	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UC	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UC	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UC	BloodMagic{1.10.2-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.11-80.jar) 
	UC	Animus{1} [Animus] (Animus-2017-04-18.jar) 
	UC	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UC	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar) 
	UC	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UC	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UC	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UC	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UC	astralsorcery{1.4.5} [Astral Sorcery] (astralsorcery-1.4.5.jar) 
	UC	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UC	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UC	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UC	badwithernocookiereloaded{1.10.2-2.12} [Bad Wither No Cookie! Reloaded] (badwithernocookiereloaded-1.10.2-2.12.jar) 
	UC	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UC	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UC	taiga{1.2.6} [Tinkers Alloying Addon] (taiga-1.10.2-1.2.6.jar) 
	UC	basemetals{2.5.0-beta4} [Base Metals] (BaseMetals-1.10.2-2.5.0-beta4.238.jar) 
	UC	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UC	bedpatch{2.2} [Bed Patch] (bedpatch-2.2-1.10.2.jar) 
	UC	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UC	BiomesOPlenty{5.0.0.2290} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2290-universal.jar) 
	UC	bloodarsenal{1.10.2-2.1.0-22} [Blood Arsenal] (BloodArsenal-1.10.2-2.1.0-22.jar) 
	UC	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UC	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UC	brandonscore{2.1.14} [Brandon's Core] (BrandonsCore-1.10.2-2.1.14.137-universal.jar) 
	UC	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UC	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UC	chisel{MC1.10.2-0.1.1.39} [Chisel] (Chisel-MC1.10.2-0.1.1.39.jar) 
	UC	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UC	chiselsandbits{12.17} [Chisels & Bits] (chiselsandbits-12.17.jar) 
	UC	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UC	cyclopscore{0.10.10} [Cyclops Core] (CyclopsCore-1.9.4-0.10.10.jar) 
	UC	IC2{2.6.252-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.252-ex110.jar) 
	UC	commoncapabilities{1.3.3} [CommonCapabilities] (CommonCapabilities-1.10.2-1.3.4.jar) 
	UC	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UC	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	UC	compatlayer{0.3.1} [compatlayer] (compatlayer-1.10-0.3.1.jar) 
	UC	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UC	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UC	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
	UC	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UC	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UC	draconicevolution{2.1.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.8.273-universal.jar) 
	UC	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.7.4.jar) 
	UC	forestry{5.2.17.388} [Forestry] (forestry_1.10.2-5.2.17.388.jar) 
	UC	eleccore{1.7.431} [ElecCore] (ElecCore-1.10.2-1.7.431.jar) 
	UC	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UC	embers{0.104} [Embers] (embers-0.104.jar) 
	UC	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UC	shetiphiancore{3.3.11} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.11.jar) 
	UC	endertanks{1.4.13} [EnderTanks] (endertanks-1.10.0-1.4.13.jar) 
	UC	modernmetals{2.5.0-beta4} [Modern Metals] (ModernMetals-1.10.2-2.5.0-beta4.19.jar) 
	UC	endmetals{1.0.4} [End Metals] (EndMetals_1.9-1.0.4.jar) 
	UC	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.6.jar) 
	UC	environmentaltech{1.10.2-0.10.6b} [Environmental Tech] (environmentaltech-1.10.2-0.10.6b.jar) 
	UC	etlunar{1.10.2-0.10.6a} [ET Lunar] (etlunar-1.10.2-0.10.6a.jar) 
	UC	evilcraft{0.10.29} [EvilCraft] (EvilCraft-1.10.2-0.10.29.jar) 
	UC	extracells{1.10.2-2.4.4a15} [Extra Cells 2] (ExtraCells-1.10.2-2.4.4a15.jar) 
	UC	Mekanism{9.2.4} [Mekanism] (Mekanism-1.10.2-9.2.4.103.jar) 
	UC	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UC	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.28-universal.jar) 
	UC	zerocore{1.10.2-0.1.1.1} [Zero CORE] (zerocore-1.10.2-0.1.1.1.jar) 
	UC	bigreactors{1.10.2-0.4.5.46} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.46.jar) 
	UC	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UC	fencejumper{1.0.1} [Fence Jumper] (fencejumper-1.10.2-1.0.1.jar) 
	UC	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UC	binniecore{2.1.0} [Binnie Core] (forestry-extras-1.10.2-2.1.0b5.jar) 
	UC	botany{2.1.0} [Binnie's Botany] (forestry-extras-1.10.2-2.1.0b5.jar) 
	UC	extrabees{2.1.0} [Binnie's Extra Bees] (forestry-extras-1.10.2-2.1.0b5.jar) 
	UC	extratrees{2.1.0} [Binnie's Extra Trees] (forestry-extras-1.10.2-2.1.0b5.jar) 
	UC	genetics{2.1.0} [Binnie's Genetics] (forestry-extras-1.10.2-2.1.0b5.jar) 
	UC	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UC	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
	UC	gendustry{1.6.5.32} [GenDustry] (gendustry-1.6.5.32-mc1.10.2.jar) 
	UC	headcrumbs{2.0.2} [Headcrumbs] (Headcrumbs-2.0.3.jar) 
	UC	theoneprobe{1.4.19} [The One Probe] (theoneprobe-1.1x-1.4.19.jar) 
	UC	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UC	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.10.2-1.1.3.jar) 
	UC	integrateddynamics{0.7.14} [Integrated Dynamics] (IntegratedDynamics-1.10.2-0.7.14.jar) 
	UC	integratedtunnels{1.2.6} [Integrated Tunnels] (IntegratedTunnels-1.10.2-1.2.6.jar) 
	UC	inventorypets{1.4.9.9b} [Inventory Pets] (inventorypets-1.10-1.4.9.9b.jar) 
	UC	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UC	ironbackpacks{1.10.2-2.2.33} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.33.jar) 
	UC	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UC	mysticalagriculture{1.5.10} [Mystical Agriculture] (mysticalagriculture-1.10.2-1.5.10.jar) 
	UC	mysticalagradditions{1.0.4} [Mystical Agradditions] (mysticalagradditions-1.10.2-1.0.4.jar) 
	UC	jaopcaagriculture{1.10.2-1.0.0.0} [JAOPCAAgriculture] (JAOPCAAgriculture-1.10.2-1.0.0.0.jar) 
	UC	jaopca{1.10.2-2.0.6.69} [JAOPCA] (JAOPCA-1.10.2-2.0.6.69.jar) 
	UC	oredictinit{1.10.2-2.0.1.65} [OreDictInit] (JAOPCA-1.10.2-2.0.6.69.jar) 
	UC	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
	UC	jehc{1.2.2} [Just Enough HarvestCraft] (jehc-1.10.2-1.2.2.jar) 
	UC	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.10.2.jar) 
	UC	jeiintegration{1.2.0.19} [JEI Integration] (jeiintegration_1.10.2-1.2.0.19.jar) 
	UC	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UC	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UC	lootbags{2.5.0} [Loot Bags] (LootBags-1.10.2-2.5.0.jar) 
	UC	lostcities{1.0.2} [The Lost Cities] (lostcities-1.1x-1.0.2.jar) 
	UC	magicbees{1.0} [MagicBees] (MagicBees-Beta-3.0.4.jar) 
	UC	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	UC	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UC	MekanismGenerators{9.2.4} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.4.103.jar) 
	UC	MekanismTools{9.2.4} [MekanismTools] (MekanismTools-1.10.2-9.2.4.103.jar) 
	UC	minecolonies{@VERSION@} [MineColonies] (minecolonies-universal-1.10.2-0.9.7587.jar) 
	UC	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UC	minetogether{unspecified} [MineTogether] (minetogether-1.10.2-1.8.7.jar) 
	UC	minetogetherserver{unspecified} [MineTogetherServer] (minetogether-1.10.2-1.8.7.jar) 
	UC	railcraft{10.3.1} [Railcraft] (Railcraft_1.10.2-10.3.1.jar) 
	UC	morebees{1.10.2-1.4.1.1} [More Bees] (morebees-1.10.2-1.4.1.1.jar) 
	UC	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.10.2.jar) 
	UC	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UC	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UC	mysticalmfrcompat{1.0.0} [Mystical MFR Compat] (mysticalmfrcompat[1.10.2]-1.0.0a.jar) 
	UC	natura{1.10.2-4.1.0.82} [Natura] (natura-1.10.2-4.1.0.82.jar) 
	UC	nethermetals{1.1.4} [Nether Metals] (NetherMetals-1.10.2-1.1.4.jar) 
	UC	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.10.2-3.3.7.jar) 
	UC	neid{1.5.3.1} [NotEnoughIDs] (NotEnoughIDs-1.5.3.1.jar) 
	UC	nuclearcraft{2.7b} [NuclearCraft] (NuclearCraft-2.7b--1.10.2.jar) 
	UC	openglider{@VERSION@} [Open Glider] (OpenGlider-1.10.2-1.0.0.jar) 
	UC	orespawn{3.2.2} [OreSpawn] (OreSpawn-1.10.2-3.2.2.104.jar) 
	UC	ProjectE{1.10.2-PE1.3.1} [ProjectE] (ProjectE-1.10.2-PE1.3.1.jar) 
	UC	p455w0rdslib{1.0.30} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.30.jar) 
	UC	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UC	plustic{5.2.1.3} [PlusTiC] (plustic-5.2.1.3.jar) 
	UC	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UC	xreliquary{1.10.2-1.3.3.664} [Reliquary] (Reliquary-1.10.2-1.3.3.664.jar) 
	UC	roots{0.208} [Roots] (roots-0.208.jar) 
	UC	sanguimancy{1.10.2-2.0.2} [Sanguimancy] (Sanguimancy-1.10.2-2.0.2.jar) 
	UC	secretroomsmod{5.1.9} [Secret Rooms 5] (secretroomsmod-1.10.2-5.1.9.jar) 
	UC	simplyjetpacks{2.1.3.55} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.1.3.55.jar) 
	UC	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UC	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UC	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UC	storagedrawersextra{1.10-1.1.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10-1.1.0.jar) 
	UC	thaumcraft{6.0.BETA6} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA6.jar) 
	UC	ThaumicJEI{1.1.1} [ThaumicJEI] (ThaumicJEI-1.1.1.jar) 
	UC	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.19-universal.jar) 
	UC	tinker_io{release 2.4.4b} [Tinker I/O] (tinker_io-1.10.2-release 2.4.4b.jar) 
	UC	TinkersAddons{1.0.6} [Tinkers' Addons] (Tinkers' Addons-1.10.2-1.0.6.jar) 
	UC	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UC	topaddons{1.10.2-0.15.0} [TOP Addons] (topaddons-1.10.2-0.15.0.jar) 
	UC	twitchcrumbs{2.0.4} [Twitchcrumbs] (Twitchcrumbs_1.10.2-2.0.4.jar) 
	UC	VeinMiner{0.38.2_1.9-127e28f} [Vein Miner] (VeinMiner-1.9-0.38.2.624+127e28f.jar) 
	UC	VeinMinerModSupport{0.38.2_1.9-127e28f} [Mod Support] (VeinMiner-1.9-0.38.2.624+127e28f.jar) 
	UC	veinminermodintegration{1.7.10-0.2.0} [Veinminer Mod Integration] (veinminermodintegration-0.6.0-1.9.4r29+2f88da6.jar) 
	UC	wanionlib{1.10.2-1.3} [WanionLib] (WanionLib-1.10.2-1.3.jar) 
	UC	waystones{2.0.13} [Waystones] (Waystones_1.10.2-2.0.13.jar) 
	UC	wct{2.1.41} [Wireless Crafting Terminal 2] (WirelessCraftingTerminal-1.10.2-2.1.41.jar) 
	UC	withercrumbs{@version@} [Wither Crumbs] (witherCrumbs-1.10.2-0.9.jar) 
	UC	Woot{1.10.2-1.4.1} [Woot] (woot-1.10.2-1.4.1.jar) 
	UE	yabba{1.10.2-0.3.0} [YABBA] (YABBA-1.10.2-0.4.0.jar) 
	UC	denseores{1.0} [denseores] (denseores-1.11-alpha-1.0.0.jar) 
	UC	unidict{1.10.2-2.9b} [UniDict] (UniDict-1.10.2-2.9b.jar) 
	UC	wrapup{1.10.2-1.0.2} [WrapUp] (WrapUp-1.10.2-1.0.2.jar) 
	Loaded coremods (and transformers): 
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.11.jar)
  shetiphian.core.asm.ClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
PlusTiC (plustic-5.2.1.3.jar)
  landmaster.plustic.asm.Transform
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
BedPatch (bedpatch-2.2-1.10.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
Brandon's Core (BrandonsCore-1.10.2-2.1.14.137-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
BaseMetals (BaseMetals-1.10.2-2.5.0-beta4.238.jar)
  com.mcmoddev.lib.asm.ASMTransformer
IC2core (industrialcraft-2-2.6.252-ex110.jar)
  
AstralCore (astralsorcery-1.4.5.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
Plugin (NotEnoughIDs-1.5.3.1.jar)
  ru.fewizz.neid.asm.Transformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.2.5a.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	minefactoryreloaded: -[1.10.2]2.9.0B1-226
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

**Comment by LatvianModder** [comment]
1.10 is no longer supported
