### ISSUE TITLE
[1.12.2] Exporting/Piping into Anti-Barrel doesn't work in 1.1.0.6

### ISSUE THREAD

**Issue by wamc2017** [LatvianModder/YABBA#68]
Hi,

I recently updated Yabba to 1.1.0.6 and FTBLib to 5.0.0.13 and since the update exporting or piping items into the Anti-Barrel doesn't work anymore. (Tried ducts from Thermal Dynamics and export buses from Applied Energistics and from Refined Storage)
Only the external storage (RS) or the storage bus (AE) seems to work, but in Yabba 1.0.11 (FTBLib 4.2.5) the exporting/piping was fine. Is this intended behavior with the new versions or is it a bug? :smile:

Thanks for the mod and best regards
wamc

**Comment by LatvianModder** [comment]
I will mark it as bug for now, and see if I can fix it on my end, but I suspect it has something to do with inventory changes I made. BUT those are in fact those mods doing things wrong then, at least to my understanding of the API

**Comment by wamc2017** [comment]
Thanks for looking into it. Tried also Mekanisms Logistical Transporter, Extrautils Transfer Nodes, Xnet and a vanilla Minecraft Hopper, nothing seems to work in 1.1.0.6 and 1.1.0.7...

**Comment by LatvianModder** [comment]
Updated to 1.1.0.8, should be fixed. Either that or its now more broken than ever before

**Comment by wamc2017** [comment]
Tried it with 1.1.0.8 but the issue is still the same...

**Comment by LatvianModder** [comment]
Is it only anti-barrel or regular barrels too?

**Comment by LatvianModder** [comment]
Ok, I think I figured out why it doesn't work, 1.1.0.9 incoming soon

**Comment by wamc2017** [comment]
Sorry, had no time to do some further testing yesterday.

In 1.1.0.7 the regular barrels was fine, only the anti-barrel is affected.

Sadly 1.1.0.9 also don't fix the problem, tried all the above listed mods again and the vanilla hopper, what I haven't discovered before is, the storage bus from AE2 only can extract from the Anti-Barrel, but can't insert, so the only thing which is working currently is the External Storage from Refined Storage...

**Comment by wamc2017** [comment]
Thanks works great now. :+1:
