### ISSUE TITLE
cant find yabba antibarrel data on sponge server

### ISSUE THREAD

**Issue by bennyb1971** [LatvianModder/YABBA#70]
one of my players is crashing on login cuz his antibarrel nbt data got too big. now i am trying to locate this nbt data so i can edit it. looked almost everywhere but cant seem to locate the nbt data. Please tell me where it is stored

**Comment by wamc2017** [comment]
Looks like it's stored inside the region file:
![yabba](https://user-images.githubusercontent.com/33242447/37770098-8b27e6bc-2dd3-11e8-8df1-e49b78ffc581.png)

**Comment by LatvianModder** [comment]
If you update Yabba, that issue should be solved
