### ISSUE TITLE
Barrels Delete Items

### ISSUE THREAD

**Issue by JoeTheSn1per** [LatvianModder/YABBA#74]
Barrels delete items when Inventory is full/the item can't enter the inventory rather than throwing it on the ground. 1.12.2 Revelation.

**Comment by LatvianModder** [comment]
Barrels with pickup upgrade or just barrels?

**Comment by JoeTheSn1per** [comment]
Regular barrels. With upgrades, without, etc. If the item can't go from the barrel inv to your inv it will delete it, whether it's one item or 10 stacks. Instead of dropping it on the ground like other mods.

**Comment by LatvianModder** [comment]
Are you sure about that? Works fine here: https://ss.latmod.com/pc/2018-04-17_20.03.48.mp4

**Comment by LatvianModder** [comment]
Maybe you are in creative mode. In that case, it works as intended, because creative mode picks up items and deletes them

**Comment by JoeTheSn1per** [comment]
Was on a server in survival mode. I don't really know how to show you but I've tested it across multiple instances with different items, barrel upgrades etc and my outcome is the same.

**Comment by JoeTheSn1per** [comment]
I'll try and get a video of it later.
