### ISSUE TITLE
Yabba item Duplication

### ISSUE THREAD

**Issue by The-Mad-Cat** [LatvianModder/YABBA#76]
This just information for mod developer. 

Ticket was almost made on FTB Revelation Bug @ https://forum.feed-the-beast.com/threads/yabba-item-duplication.278025/

> When have ME Import Bus connect to Yabb barrel and use chest transporter you get barrel in transporter (like you should) and drop item of barrel on floor.
> 
> Mod & Version Yabba 1.1.0.9
> Applied Energistics 2 rv5-stable-11
> Chest Transporter Version 1.12.2-2.8.8 (2.8.8)
> 
> Link to log file
> 
> Is it repeatable? Place yabba barrel (antibarrel or iten barrel) under ME Import Bus. (ME should be connect to ME system).
> Try pickup barrel using chest transporter, which mine was obsidian level
> 
> Known Fix Update Yabba most likely

**Comment by LatvianModder** [comment]
Already fixed
