### ISSUE TITLE
Texture and Model Issues

### ISSUE THREAD

**Issue by Fortist** [LatvianModder/YABBA#78]
![2018-04-16_00 36 18](https://user-images.githubusercontent.com/5784537/38816470-23afc0be-4164-11e8-8523-3da753519276.png)

And the model viewer has the basic barrel model on every one of them, but they still create their named model when used, however.

Also, I noticed when using texture packs with certain edits (CTM) to certain vanilla blocks made your barrel item disappear. At least in previous versions.

Version 1.1.2.5.

**Comment by LatvianModder** [comment]
O_O

**Comment by LatvianModder** [comment]
I can't reproduce the issue. Does this happen always?
