### ISSUE TITLE
Linking Barrels

### ISSUE THREAD

**Issue by MrRoooo** [LatvianModder/YABBA#79]
What happened to the linking barrels?  

**Example**:
Barrels A has Wheat.
Barrel B has nothing.

Link A to B = Barrel B now has Wheat. 

Both share the same item with the same amount.  If you take 5 out of B, both A & B will have 5 less.

**Comment by MrRoooo** [comment]
BTW - LOVE your mod!

**Comment by LatvianModder** [comment]
They will be called Phantom Barrels, and Soon™️ : https://github.com/LatvianModder/YABBA/issues/45
