### ISSUE TITLE
request to publish

### ISSUE THREAD

**Issue by monororo** [LatvianModder/YABBA#84]
hello author, I come from a minecraft mod website(https://www.mcmod.cn). This website includes contents about mod info and mod files. Could you please allow me to publish your mod on this site? I shall submit your mod files on this site, and write a brief wiki about it.
P.S. Sorry for my bad english. And this site is made for Chinese, so I will apologize for any inconvenience causing.

**Comment by LatvianModder** [comment]
Sure, just link to https://minecraft.curseforge.com/projects/yabba
