### ISSUE TITLE
compound item barrel cannot transfer item into barrel

### ISSUE THREAD

**Issue by monororo** [LatvianModder/YABBA#88]
Suggests there is a barrel connected with connector and compound item barrel, and some stones is in the barrel. If input stones into connector, the stones will go to barrel; but input into compound will cause stones stored at compound, not barrel. They can be extracted with hopper, but not with bare hand. If interact with connector, it will show how many stones are in the compound. So may be stones should have went to barrel instead of stayed at compound?

**Comment by Laserman2** [comment]
Yeah, I can second this. Items seem to get stuck in the compound item connectors instead of going into the barrels.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/YABBA/issues/103
