### ISSUE TITLE
Upgrades don't update max.

### ISSUE THREAD

**Issue by Trinsec** [LatvianModder/YABBA#9]
If I sneak and look at the barrel, I see stuff like 4096/4096. If I slap a Wooden to Iron Barrel Upgrade on it, and look again, it still says 4096/4096, and adding items lead to stuff like 5000/4096. The max didn't get updated.
~~Using 1.1.10.2-0.3.0~~ (we're on FTB Beyond)
Actually, we seem to have 1.10.2-0.4.0 installed, but the mod controls info tells us 0.3.0? Looks like the mcmod.info in the .jar didn't get updated for this.

**Comment by kojakk** [comment]
Getting something similar (also FTB Beyond) but I hadn't tried exceeding the max so I thought the upgrade just didn't take.

**Comment by LatvianModder** [comment]
Yeah, I made 0.4.0 to work with 0.3.0 so the beyond test server didnt have to update clients when we were testing it. Anyway, yeah, the actual max size increeses, it just doesnt display the correct number, so its just a visual glitch. It works with infinity upgrade though
