### ISSUE TITLE
Yabba Barrel Dupe

### ISSUE THREAD

**Issue by Zero9o1o** [LatvianModder/YABBA#90]
Yabba, Version: 1.1.2.9
Actually Additions, Version: 1.12.2-r135
Chest Transporter, Version: 1.12.2-2.8.8
Thermal Dynamics, Version: 1.12.2-2.5.1.14
RFTools, Version: 1.12-7.53
Applied Energistics 2, Version: rv5-stable-11

Pack: FTB Continuum, Version: 1.3.1

It seems when an "Auto-Breaker" breaks a "Item Barrel" it drop one in the world which is the one that has items in it but the "Auto-Breaker" has a new "Item Barrel" in its inventory, the new "Item Barrel" is empty.

A similar thing happens when you pick up a "Item Barrel" with a "Chest Transporter" which is sitting on a duct from Thermal Dynamics, The original "Item Barrel" is in "Chest Transporter" and a new "Item Barrel" is dropped on the ground.

The "Builder" from RFTools using a quarry card ( Tested with a clearing quarry card ) will do the same as the "Auto-Breaker".

The "ME Annihilation Plane" from Applied Energistics 2 also makes a new "Item Barrel"

This seems to be similar to issue #76

**Comment by LatvianModder** [comment]
It only dupes the barrel, without contents? That's good at least

**Comment by Zero9o1o** [comment]
Yea only the barrel gets duped

**Comment by LatvianModder** [comment]
After some testing it turns out I'm not doing anything wrong, because vanilla shulker boxes can be duped in the exact same way. I tested with AA Auto-Breaker and ME Annihilation Plane, and I will simply ask Chest Transporter to stop supporting it and will add easier way to drop item without taking any items
