### ISSUE TITLE
Crash on launching with Astral sorcery

### ISSUE THREAD

**Issue by karelmikie3** [LatvianModder/YABBA#91]
mc version: 1.12.2
forge: 14.23.4.2705
astralsorcery: 1.12.2-1.9.3
ftbLib: 5.2.0.24
YABBA: 1.1.2.11

Crash occurs in post initialization crash started in version 1.1.2.11. No such crash occurred in 1.1.2.10.
[log and crash report](https://paste.ee/p/oxfRq)

**Comment by Hubry** [comment]
Woo, another one to add to HellFirePvP/AstralSorcery#762...

**Comment by Matakor** [comment]
Getting a crash as well, however with AS and IC2.
IC2 is erroring out on my end specifically. 
[Crashlog here](https://pastebin.com/R1cCn31H)

**Comment by DaggerTM** [comment]
Crash Happens with JEI for me:
https://github.com/mezz/JustEnoughItems/issues/1290
