### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by tfox83** [LatvianModder/YABBA#94]
From Continuum

Modpack Version: 1.3.1

Issue: Whenever I use a chest transporter on a YABBA barrel connected with an itemduct from thermal dynamics it will create an extra barrel (without the items of the original).

Is it Repeatable?: Yes.

Mod/s Affected: YABBA 1.1.2.9 and Thermal Dynamics 2.5.1.14

Known Fix: Unknown

OP:
https://github.com/FTBTeam/FTB-Continuum/issues/320

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/YABBA/issues/90
