### ISSUE TITLE
Antibarrel GUI not texture-pack friendly?

### ISSUE THREAD

**Issue by Matakor** [LatvianModder/YABBA#98]
Maybe I'm just blind or something, but I can't find the GUI for the antibarrel. It doesn't seem to be contained in the mod itself, and it does seem to stretch a lot of it's textures. Is it only using ingame textures? or?

Can we get an option to make our own texture for the GUI?

**Comment by LatvianModder** [comment]
No, but I will change soon how FTBLib loads its textures, that should fix it
